/* (C)2026 Christian Schnapka / Macstab GmbH */
package com.macstab.oss.redis.laned.config;

import com.macstab.oss.redis.laned.strategy.LaneSelectionStrategyType;

import lombok.Builder;
import lombok.Value;

/**
 * Immutable configuration source for Redis Laned settings.
 *
 * <p>This class represents the resolved configuration from any source (annotation, YAML, defaults),
 * used internally by Spring Boot auto-configuration.
 *
 * <p><strong>Configuration Precedence:</strong>
 *
 * <ol>
 *   <li>{@code @LanedRedisConnection} annotation (highest priority)
 *   <li>YAML/properties ({@code spring.redis.laned.*})
 *   <li>Defaults (lowest priority)
 * </ol>
 *
 * <p><strong>Construction:</strong> This class uses Lombok's {@code @Value} and {@code @Builder}
 * annotations which generate:
 *
 * <ul>
 *   <li>All-args constructor: {@code LanedRedisConfigurationSource(int lanes,
 *       LaneSelectionStrategyType strategyType, boolean metricsEnabled, ConfigurationSourceType
 *       sourceType)}
 *   <li>Builder: {@code builder()} returns a builder instance
 *   <li>Getters: {@code getLanes()}, {@code getStrategyType()}, etc.
 *   <li>Equals/HashCode/ToString: Standard value object implementations
 * </ul>
 *
 * <p>Use {@code builder()} to construct instances or {@link #defaultConfig()} for defaults.
 *
 * @author Christian Schnapka - Macstab GmbH
 */
@Value
@Builder
public class LanedRedisConfigurationSource {

  /** Number of connection lanes. */
  int lanes;

  /** Lane selection strategy type. */
  LaneSelectionStrategyType strategyType;

  /** Whether metrics are enabled. */
  boolean metricsEnabled;

  /** Configuration source type (for debugging/logging). */
  ConfigurationSourceType sourceType;

  /**
   * Configuration source types (for precedence tracking).
   *
   * <p>Used internally to track where configuration originated (annotation, YAML, or defaults) for
   * logging and debugging purposes.
   *
   * <p>Standard Java enum with implicit no-arg private constructor (generated by compiler).
   */
  public enum ConfigurationSourceType {
    /** Configuration from {@code @LanedRedisConnection} annotation (highest priority). */
    ANNOTATION,

    /** Configuration from YAML/properties file. */
    PROPERTIES,

    /** Default configuration (fallback). */
    DEFAULT;

    /**
     * Private enum constructor (implicit, generated by Java compiler).
     *
     * <p>Enums cannot be instantiated directly. Use constants {@link #ANNOTATION}, {@link
     * #PROPERTIES}, or {@link #DEFAULT}.
     */
    ConfigurationSourceType() {
      // Implicit enum constructor - no initialization needed
    }
  }

  /**
   * Create default configuration.
   *
   * @return default config (lanes=4, strategy=ROUND_ROBIN, metrics=true)
   */
  public static LanedRedisConfigurationSource defaultConfig() {
    return LanedRedisConfigurationSource.builder()
        .lanes(4)
        .strategyType(LaneSelectionStrategyType.ROUND_ROBIN)
        .metricsEnabled(true)
        .sourceType(ConfigurationSourceType.DEFAULT)
        .build();
  }
}
