#!/bin/bash
# Setup Testcontainers for Docker-in-Docker
# Run this ONCE inside your dev container: ./scripts/setup-testcontainers-dind.sh

set -e

echo "=== Testcontainers DinD Setup ==="

# Check if we're in a Docker container
if [ ! -f /.dockerenv ]; then
    echo "⚠️  Not running in Docker container - skipping DinD configuration"
    exit 0
fi

echo "✓ Docker container detected"

# Check if Docker socket is accessible
if [ ! -S /var/run/docker.sock ]; then
    echo "❌ /var/run/docker.sock not found or not a socket"
    exit 1
fi

echo "✓ Docker socket accessible"

# Create ~/.testcontainers.properties
PROPS_FILE="$HOME/.testcontainers.properties"
cat > "$PROPS_FILE" << 'EOF'
# Testcontainers Docker-in-Docker configuration
# Auto-generated by setup-testcontainers-dind.sh

# Force Unix socket strategy
docker.host=unix:///var/run/docker.sock

# Disable Ryuk (cleanup container - unreliable in DinD)
testcontainers.ryuk.disabled=true

# Disable reuse (containers cleaned up after tests)
testcontainers.reuse.enable=false
EOF

echo "✓ Created $PROPS_FILE"
echo ""
echo "Configuration:"
cat "$PROPS_FILE"
echo ""
echo "✅ Testcontainers configured for DinD"
echo "   Now run: ./gradlew test --tests \"*IntegrationTest\""
